services:
  db:
    image: postgres:16
    container_name: matchday_db
    environment:
      POSTGRES_DB: matchday
      POSTGRES_USER: matchday
      POSTGRES_PASSWORD: matchday
    ports:
      - "5432:5432"
    volumes:
      - matchday_pg:/var/lib/postgresql/data

volumes:
  matchday_pg:
